server {
    listen 80;
    root /usr/share/nginx/html/help;
    index index.html;

    add_header Cache-Control "no-cache, must-revalidate";

    location / {
        try_files $uri $uri/ $uri.html =404;
    }
}
